name: laundry_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus:
  shared_preferences: ^2.2.0
  cached_network_image: ^3.4.1
  flutter_svg:
  google_sign_in: ^6.1.4
  country_pickers: ^3.0.1
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.1
  intl: ^0.19.0
  colorful_safe_area: ^1.0.0
  calendar_date_picker2: ^1.1.7
  pinput: ^5.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
